package buildimage

import (
	"strings"
	"testing"
)

func TestGenerateDockerfile(t *testing.T) {
	content := string(GenerateDockerfile("gc-agent:latest"))

	// Must contain ARG BASE with the default image.
	if !strings.Contains(content, "ARG BASE=gc-agent:latest") {
		t.Error("missing ARG BASE=gc-agent:latest")
	}

	// Must copy workspace.
	if !strings.Contains(content, "COPY --chown=gcagent:gcagent workspace/ /workspace/") {
		t.Error("missing COPY workspace/")
	}

	// Must touch the ready sentinel.
	if !strings.Contains(content, "touch /workspace/.gc-workspace-ready") {
		t.Error("missing touch .gc-workspace-ready")
	}

	// Must expose baked GR7N scripts and wrap gh with the GitHub App token helper.
	if !strings.Contains(content, `ENV PATH="/workspace/scripts:`) {
		t.Error("missing /workspace/scripts on PATH")
	}
	if !strings.Contains(content, "/workspace/scripts/github-app-token.sh") {
		t.Error("missing gh GitHub App token wrapper")
	}

	// Must set USER.
	if !strings.Contains(content, "USER gcagent") {
		t.Error("missing USER gcagent")
	}

	// Must start with the generated-by comment.
	if !strings.HasPrefix(content, "# Generated by: gc build-image") {
		t.Error("missing generated-by comment")
	}
}

func TestGenerateDockerfileCustomBase(t *testing.T) {
	content := string(GenerateDockerfile("my-registry/custom:v2"))

	if !strings.Contains(content, "ARG BASE=my-registry/custom:v2") {
		t.Errorf("expected custom base image, got:\n%s", content)
	}
}
