// Package buildimage assembles Docker build contexts for prebaked agent images.
package buildimage

import (
	"fmt"
	"strings"
)

// GenerateDockerfile returns Dockerfile content for a prebaked agent image.
// The generated image copies the pre-staged workspace directory and touches
// the ready sentinel so the entrypoint skips the wait.
func GenerateDockerfile(baseImage string) []byte {
	// Reject newlines to prevent Dockerfile directive injection.
	if strings.ContainsAny(baseImage, "\n\r") {
		baseImage = strings.NewReplacer("\n", "", "\r", "").Replace(baseImage)
	}
	const tmpl = `# Generated by: gc build-image
ARG BASE=%s
FROM ${BASE}
USER root
COPY --chown=gcagent:gcagent workspace/ /workspace/
ENV PATH="/workspace/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
RUN set -eu; \
    if [ -x /usr/bin/gh ]; then \
      printf '%%s\n' \
        '#!/usr/bin/env sh' \
        'if [ -z "${GH_TOKEN:-}" ] && [ -x /workspace/scripts/github-app-token.sh ]; then' \
        '  token="$(/workspace/scripts/github-app-token.sh 2>/dev/null || true)"' \
        '  if [ -n "$token" ]; then' \
        '    export GH_TOKEN="$token"' \
        '    if [ -z "${GITHUB_TOKEN:-}" ]; then' \
        '      export GITHUB_TOKEN="$token"' \
        '    fi' \
        '  fi' \
        'fi' \
        'exec /usr/bin/gh "$@"' \
        > /usr/local/bin/gh; \
      chmod 0755 /usr/local/bin/gh; \
    fi; \
    touch /workspace/.gc-workspace-ready
USER gcagent
`
	return []byte(fmt.Sprintf(tmpl, baseImage))
}
